version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/python:3.6 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: pytest --cov=lib2 tests/ --cov-report html 
